jgm/pandoc-templates

default.revealjs
`reveal.js` no longer ships with /css/reveal.min.css or /js/reveal.min.js, so template should refer to non-minified original files.
=> Link to non-minified reveal.js JS and CSS files

default.revealjs
Use up-to-date theme as link convention for revealjs. Leave old theme as
config option just in case. Match current revealjs behavior of
defaulting to "black" theme.
Fixes #80
Signed-off-by: Aaron Browne <aaron0browne@gmail.com>
=> Fix revealjs theme functionality

default.latex
This should make those behave more like sections, as per https://github.com/jgm/pandoc/issues/1658
=> Redefine (sub)paragraphs in default LaTeX template

default.latex
This uses TeX primitives, since using `\@ifundefined` would define `\paragraph` as `\relax` if it's not defined, which could be (a) disruptive and (b) would not report on subsequent errors with `\paragraph`, if it's used anywhere else in the document.
=> Fix paragraph undefined problem

default.latex
If the link color in the table of contents is a different one from default, it should be customisable. Some may see the default black and not realise that the table is interactive - especially if the viewer sees other parts of the document that could be interactive but are not for that particular build e.g. citations.
=> Add option for ToC color

default.epub, default.epub3
The EPUB metadata description specifies "role" for creators, not "type": 
http://pandoc.org/README.html#epub-metadata
This fixed the two epub templates to use the correct syntax.
=> Use creator.role instead of creator.type

default.latex
Works only with xelatex.
This is not a big deal since when it hits on a utf8 unknown char (say Asian script), pandoc suggests to switch to the xelatex engine.
This is already changing my life! :dancer:
=> Support for Asian languages, CJKmainfont label

default.latex
Follow-up to pull request #99 
It is often good practice to set a slightly bigger font size for Asian characters compared to Latin ones.
Which could be reflected by something like below:
```
mainfont: Linux Libertine
CJKmainfont: Noto Sans S Chinese Light
CJKoption: Scale=1.05
title: Spelling Rules of Pinyin
subtitle: 汉语拼音拼写规则
```
=> Pass options to CJKmainfont (CJKoption)

default.context
ConTeXt template description lists: activate hanging text so if you have description keys that have not the same length, the paragraphs are still aligned and look nice.
Before:
After:
=> ConTeXt template description lists

default.beamer
Beamer allows configuring inner and outer themes.
This patch allows pandoc's user to set the expected part of the theme.
=> Add support for inner/outer theme

default.latex
This allows one to modify the settings within a font package (or in an OpenType font, for XeLaTeX), for example:
```markdown
---
mainfont: "Arno Pro"
mainfontoptions: "Ligatures=TeX,Numbers=OldStyle,Numbers=Proportional"
...
These numerals will be proportional: 123.
```
=> Allow for font options in LaTeX.

default.latex
There are several conflicts that are raised when you use tufte-handout
layout with the default.latex template, namely `hyperref` and `color`, which
are already loaded by the class.
This commit enables to only load `hyperref` and `color` packages if they
are not already loaded (by tufte-handout).
=>  Deal with conflicts with tufte-handout.cls

default.latex
This fixes a problem with complex superscripts/subscripts, by removing use of the `realscripts` package: see wspr/realscripts/issues/6. None of the other features provided by `xltxtra` are necessary to Pandoc. The `fontspec` package already loads `xunicode` (since at least 2010).
=> Remove xltxtra, xunicode from LaTeX template.

default.beamer, default.latex
Adds new language and bidi variables; removes duplicated `\VerbatimFootnotes`.
The standard `fontspec` variables, previously omitted, are now included. Beamer defaults to the font set as `sansfont`. If `mainfont` is set, the `serif` font theme will also be used, which uses this for the slide text (does not have to be a serif font per se).
The paragraph indentation and use of the `url` package seem to have had no visible effect, and have been removed.
=> Realign LaTeX and beamer templates.

default.latex
Add a variable "hidelinks" to allow to hide links as plain text in LaTeX. It removes any color and borer. The variable does not need any particular argument  (see https://www.tug.org/applications/hyperref/manual.html)
=> Enable to hide links as plain text (hyperref option)

default.beamer, default.latex
In the spirit of the recent additions to the template variables, this adds three more:
- `fontenc` allows for the use of an encoding other than `T1`: closes #112. (See <http://mirror.ctan.org/macros/latex/doc/encguide.pdf>.)
- `indent` and `subparagraph` allow the Pandoc overrides for these features to be disabled (while leaving them on by default).
I will submit updates to the README if you decide to integrate these.
(I promise that this is the last of the changes in the recent bout of template updates.)
=> Add fontenc, indent, subparagraph variables to LaTeX.

default.revealjs
All configuration options are now available as variables, but are only be included in final document if set (reveal.js uses defaults otherwise).
If you approve of this, should we simply indicate that all reveal.js configuration options listed at <https://github.com/hakimel/reveal.js#configuration> can be set as variables, rather than listing all these in the documentation?
Note that <https://github.com/jgm/pandoc/blob/82b3e0ab97a67188f0886dd6b758aa8d0ccd1064/src/Text/Pandoc/Writers/HTML.hs#L195> will set the `center` variable to `true` by default, which doesn't do any harm, but isn't necessary with this template.
=> Update reveal.js template from 3.1 source.

default.beamer, default.latex
This avoids the ‘use `Ligatures=TeX` instead of `Mapping=tex-text`’ warning when using LuaTeX. The [manual](http://mirrors.ctan.org/macros/latex/contrib/fontspec/fontspec.pdf) clarifies: 'for consistency `Ligatures=TeX` will perform the same function as `Mapping=tex-text`.'
=> Use Ligatures=TeX for fontspec.

default.context
This allows ContTeXt to approach parity with the LaTeX template. Dropping support for MkII (which hasn't been under development since 2007) allows for a simpler and more generic template; hope this is acceptable.
=> Expand ConTeXt variables; drop MkII support.

default.context
Sets default link colour to black with normal style (default is bolded red/green links), per the discussion in #138. Provides heading styles for all section types applied by Pandoc.
=> ConTeXt link colour to black; define all sections.

default.latex
The different usage for `xetex` appears to have been a workaround for bugs fixed in 2009 (see my question on this at <http://tex.stackexchange.com/questions/273339/what-hyperref-options-should-be-used-for-correct-unicode-output>), meaning that the same options can be used for all engines. The `subtitle` is used to set the PDF subject, following ConTeXt. The `bookmarks` option is enabled by default and does not need to be repeated.
=> Simplify hyperref usage.

default.asciidoc
AsciiDoctor did not parse previous output correctly. See <http://asciidoctor.org/docs/user-manual/#keywords> on keywords, <http://asciidoctor.org/docs/user-manual/#author-and-email> on author, <http://asciidoctor.org/docs/user-manual/#user-abstract> for abstract.
AsciiDoctor can also take a subtitle, but Pandoc would need to switch to writing ATX-style headers to make this possible (though I think this would also allow for a simplification of the code, as it would likely make the `titleblock` variable unnecessary).
=> Fix author, date in AsciiDoc; add keywords, abstract.

default.html, default.html5, default.revealjs, default.s5, default.slideous, default.slidy
This allows `keywords` in all HTML templates (also part of #143), and adds lang, dir, quotes where not included previously. Always makes display of author and date conditional. Fixes a few minor issues with display of S5 title slide.
=> Add keywords to HTML templates; realign.

default.beamer, default.context, default.latex
Edited:
Apologies for the omnibus pull request; can flatten this into one commit or separate them out as desired. This provides several minor improvements:
- Formatting of some conditionals is adjusted to provide cleaner spacing and punctuation in generated preamble.
- `$for$` is always provided where the user might want to use multiple options (does not change existing functionality).
- `hyperref` link rendering revised per discussion in https://github.com/jgm/pandoc-templates/commit/a84f822c30fde1802131c1c7d69d6ebae4550f72:
- the `hidelinks` option is now effectively the default (and has been removed as a separate option), rather than setting all links to black;
- link colours can be enabled more easily (using a slightly darker version of the old Pandoc defaults) using a new …
=> ConTeXt/LaTeX/Beamer clean-up

default.revealjs
Removed quotes from around values inserted for parallaxBackgroundHorizontal and parallaxBackgroundVertical. reveal.js expects these values to be integers, not strings.
=> reveal.js - Fix broken parallaxBackgroundHorizontal and parallaxBackgroundVertical support.

default.latex
The title of the document in the `hyperref` settings or in the header/footnotes would otherwise be "${title}0.5em${subtitle}".
=> Issue for title.meta when subtitle is set

default.context
Thanks to Rik Kabel on pandoc-discuss.
=> Revert use of \setuphead for ConTeXt title block.

default.context
simplefonts is required, since ConTeXt stable from TeX Live 2015 seems to have problem with some typefaces when not used.
@adunning, I selected _DejaVu Serif_ as Greek typeface. Could you check the new template and propose another typeface fallback for Greek if desired?
Many thanks for your help.
=> font loading with simplefonts

default.man
For some reason, `.nh` does not work if specified _prior to_ `.TH`. If `.nh` is below `.TH`, hyphenation is properly disabled.
=> Make sure disabling hyphenation actually works.

default.latex
The color options are only used for setting the link colour; it is otherwise redundant (someone wanting to add colour to other parts of the document will likely have more complex needs).
=> Make color option change dependent on colorlinks.

default.latex
=> Make \euro conditional for XeTeX/LuaTeX.

default.beamer
Implements the change made for LaTeX in <https://github.com/jgm/pandoc-templates/commit/e45a3fac77e5bd876b20a6b8a0dcbf54f5aa12ab>.
=> Make \euro conditional in Beamer for XeTeX/LuaTeX.

default.beamer, default.latex
This will allow the user to set a 'biblatexoptions' variable (e.g. 'style=...' which will be passed to biblatex.sty.
=> Biblatex options

default.beamer
If themes are loaded after fonts then they can override fonts. Otherwise, what the themes set will be overridden by the fallback loading of lmodern.sty.
=> Moved themes after fonts

default.latex
Adding the $institute variable allows me to use pandoc for writing
papers using the llncs document class.
http://www.springer.com/computer/lncs/lncs+authors?SGWID=0-40209-0-0-0
=> Add $institute to the latex template

default.latex
Adding ability to define custom font families. Needed for correct polyglossia operation with Cyrillic fonts and perhaps can find some other usages.
The original error to fix was: `! TeX capacity exceeded, sorry [input stack size=5000].`
An example usage in YAML metadata:
```yaml
fontfamilies:
- name: \cyrillicfont
font: Liberation Serif
- name: \cyrillicfonttt
options: Scale=MatchLowercase
font: Liberation Mono
```
=> Custom font families

default.beamer, default.latex
The $biblatexoptions$ will be passed directly to biblatex. This means that runtime options are allowed. Addresses https://github.com/jgm/pandoc-templates/issues/201
=> Pass $biblatexoptions$ directly to biblatex

default.latex
Fixes https://github.com/jgm/pandoc-templates/issues/204 by adding a dummy `\institute` command.
=> Added `\institute`

default.latex
The beamerarticle package needs to be loaded directly after the documentclass
declaration. Loading it later (e.g. using the -H option) leads to several
errors due to package dependencies.
This patch also introduces a new variable "beamerarticle" to activate the
beamerarticle package.
=> Load "beamerarticle" first (if needed)

default.beamer
Adding ability to define custom font families. Needed for correct `polyglossia` operation with Cyrillic fonts and perhaps can find some other usages. Example usage in YAML metadata:
```
fontfamilies:
- name: \cyrillicfont
font: Liberation Serif
- name: \cyrillicfonttt
options: Scale=MatchLowercase
font: Liberation Mono
```
=> Custom font families for beamer template

default.html5
Every heading element semantically creates a new section.  Three
consecutive heading elements, e.g. `<h1></h1>`, `<h2></h2>`,
`<h3></h3>`,  semantically equivallent to a section with two
subsections.  This is not the intended meaning of subtitle, author, and
date, making plain `<p>` elements the better choice.  This is one of
the W3C's [common idioms].
This change is the result of discussions on issue jgm/pandoc#3119.
[common idioms]: https://www.w3.org/TR/html5/common-idioms.html#common-idioms
Fixes: jgm/pandoc#3119
=> Put only one heading element in top-level header

default.latex
This restores Pandoc's defaults after applicaiton of changes in
https://github.com/jgm/pandoc/pull/3093.
=> LaTeX: Set figure placement defaults.

default.beamer
I'm not sure if there is a reason why these were withheld from the
default beamer template, but it seemed to work when I added it in to my
Beamer project.
There was some previous discussion about this at jgm/pandoc#1600.
=> Add hypersetup options to beamer templates

default.dzslides
For instance, if you try to compile the following markdown code with pandoc (using 1.12):
``` markdown
Page 1
------
This is a very long code line that will appear on every slide even on page three
Page 2
------
My content
Page 3
------
My last content
```
using this command:
pandoc -s -t dzslides test.md -o test.html
the long code line will appear on every slide. Using pre-wrap fixes the problem by forcing word wrap of code. The only drawback is that it requires IE 8 [according to MDN](https://developer.mozilla.org/fr/docs/Web/CSS/white-space), which make it less compatible.
A workaround it to wrap the code when writing it, but if you consider inline code tags using the accents \`\` in markdown this is not possible.
=> DZSlides: Force word wrapping in code tags

default.latex
The option pdfkeywords from hyperref needs keywords separated with a comma `,` instead of a semicolon `;`.
=> Keyword definition used wrong separator

default.latex
This change allows me to tweak microtype settings. In particular, I am interested in being able to change font stretching/shrinking values.
=> Allow passing options to `microtype` LaTeX package

default.latex
This implements suggestion from geometry package manual section 9 Known
problems:
> With mag ≠ 1000, no truedimen and hyperref, hyperref should be loaded
> before geometry. Otherwise the resulted PDF size will become wrong.
=> LaTeX: Load geometry package after hyperref.

default.latex
Use `mathspec` only with XeLaTeX on request.
It seems that [`mathspec`](http://tex.stackexchange.com/a/118273/28495) serves a slightly different purpose than `unicode-math`. For consistency between XeLaTeX and LuaLaTeX, it seems better to prefer `unicode-math`. This pull request still allows use of `mathspec` when it is request by defining synonymous variable.
I suggest this to be applied instead of #183 and #103.
=> Use `unicode-math`.
